services:
  mcdesk-node1: # This is also the hostname of the container within the Docker network (i.e. https://mcdesk-node1/)
    image: mcdeskproject/mcdesk:latest
    container_name: mcdesk-node1
    environment:
      - cluster.name=mcdesk-cluster # Name the cluster
      - node.name=mcdesk-node1 # Name the node that will run in this container
      - discovery.seed_hosts=mcdesk-node1,mcdesk-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=mcdesk-node1,mcdesk-node2 # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD} # Sets the demo admin user password when using demo configuration (for MCdesk 2.12 and later)
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the mcdesk user - set to at least 65536
        hard: 65536
    volumes:
      - mcdesk-data1:/usr/share/mcdesk/data # Creates volume called mcdesk-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - mcdesk-net # All of the containers will join the same Docker bridge network
  mcdesk-node2:
    image: mcdeskproject/mcdesk:latest # This should be the same image used for mcdesk-node1 to avoid issues
    container_name: mcdesk-node2
    environment:
      - cluster.name=mcdesk-cluster
      - node.name=mcdesk-node2
      - discovery.seed_hosts=mcdesk-node1,mcdesk-node2
      - cluster.initial_cluster_manager_nodes=mcdesk-node1,mcdesk-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - mcdesk-data2:/usr/share/mcdesk/data
    networks:
      - mcdesk-net
  mcdesk-dashboards:
    image: mcdeskproject/mcdesk-dashboards:latest # Make sure the version of mcdesk-dashboards matches the version of mcdesk installed on other nodes
    container_name: mcdesk-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to MCdesk Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://mcdesk-node1:9200","https://mcdesk-node2:9200"]' # Define the MCdesk nodes that MCdesk Dashboards will query
    networks:
      - mcdesk-net

volumes:
  mcdesk-data1:
  mcdesk-data2:

networks:
  mcdesk-net:
